### ISSUE TITLE
WebDAV connected but no song loaded

### ISSUE THREAD

**Issue by renmu123** [icidasset/diffuse#374]
Hi, I tried diffuse.sh and successfully added my WebDAV server. But nothing shows.

I have configured CORS correctly.

I use the [wsgidav](https://github.com/mar10/wsgidav)  as serve.

Here is the request from dev tools.

```xml
<?xml version="1.0" encoding="utf-8" ?>
<ns0:multistatus
    xmlns:ns0="DAV:">
    <ns0:response>
        <ns0:href>/music/</ns0:href>
        <ns0:propstat>
            <ns0:prop>
                <ns0:resourcetype>
                    <ns0:collection />
                </ns0:resourcetype>
                <ns0:creationdate>2022-12-08T15:22:13Z</ns0:creationdate>
                <ns0:getlastmodified>Thu, 08 Dec 2022 15:22:26 GMT</ns0:getlastmodified>
                <ns0:displayname>music</ns0:displayname>
                <ns0:lockdiscovery />
                <ns0:supportedlock>
                    <ns0:lockentry>
                        <ns0:lockscope>
                            <ns0:exclusive />
                        </ns0:lockscope>
                        <ns0:locktype>
                            <ns0:write />
                        </ns0:locktype>
                    </ns0:lockentry>
                    <ns0:lockentry>
                        <ns0:lockscope>
                            <ns0:shared />
                        </ns0:lockscope>
                        <ns0:locktype>
                            <ns0:write />
                        </ns0:locktype>
                    </ns0:lockentry>
                </ns0:supportedlock>
            </ns0:prop>
            <ns0:status>HTTP/1.1 200 OK</ns0:status>
        </ns0:propstat>
    </ns0:response>
    <ns0:response>
        <ns0:href>/music/aaa.mp3</ns0:href>
        <ns0:propstat>
            <ns0:prop>
                <ns0:resourcetype />
                <ns0:creationdate>2022-12-08T14:41:21Z</ns0:creationdate>
                <ns0:getcontentlength>9155491</ns0:getcontentlength>
                <ns0:getcontenttype>audio/mpeg</ns0:getcontenttype>
                <ns0:getlastmodified>Thu, 01 Dec 2022 13:08:04 GMT</ns0:getlastmodified>
                <ns0:displayname>aaa.mp3</ns0:displayname>
                <ns0:getetag>83faaa386595744d257bc07e75db0cd9-1669900084-9155491</ns0:getetag>
                <ns0:lockdiscovery />
                <ns0:supportedlock>
                    <ns0:lockentry>
                        <ns0:lockscope>
                            <ns0:exclusive />
                        </ns0:lockscope>
                        <ns0:locktype>
                            <ns0:write />
                        </ns0:locktype>
                    </ns0:lockentry>
                    <ns0:lockentry>
                        <ns0:lockscope>
                            <ns0:shared />
                        </ns0:lockscope>
                        <ns0:locktype>
                            <ns0:write />
                        </ns0:locktype>
                    </ns0:lockentry>
                </ns0:supportedlock>
            </ns0:prop>
            <ns0:status>HTTP/1.1 200 OK</ns0:status>
        </ns0:propstat>
    </ns0:response>
</ns0:multistatus>
```

**Comment by icidasset** [comment]
👋 Diffuse is configured to use the `D:` property namespace, not `ns0:`. I didn't realise different namespaces were actually used, I'll see if I can adjust the parser to deal with this. I'm working on a big PR at the moment, and don't have a lot of time in general to work on Diffuse so this could take a while. Maybe you can configure `wsgidav` to use the `D:` or `d:` namespace? 🤔 

Parser code lives here if you're interested: https://github.com/icidasset/diffuse/blob/main/src/Library/Sources/Services/WebDav/Parser.elm#L49

**Comment by renmu123** [comment]
Thank for your help, can you recommand some webdav servers for me which support diffuse?

**Comment by Netherquark** [comment]
Hey, when I was trying to setup WebDAV with diffuse, icidasset recommended WebDAV go, a WebDAV server written in go as per the name

**Comment by renmu123** [comment]
This is my config for [webdav](https://github.com/hacdias/webdav).


```yaml
address: 0.0.0.0
port: 19000
auth: true
tls: false
prefix: /
debug: false

# Default user settings (will be merged)
scope: .
modify: true
rules: []

# CORS configuration
cors:
  enabled: true
  credentials: true
  allowed_hosts:
    - http://127.0.0.1:12345 # my local diffuse
  allowed_headers:
    - Depth
    - authorization
    - X-PINGOTHER
    - Content-Type
    - Range
    - Accept-Encoding
    - Origin
    - Host
    - Referer
  allowed_methods:
    - GET
    - PROPPATCH
    - PROPFIND
    - OPTIONS
  exposed_headers:
    - Content-Length
    - Content-Range
    - Allow
    - Content-Type
    - Origin

users:
  - username: admin
    password: admin
    scope: "" # path

```

l run local diffuse with caddy, this is  my config 

Caddyfile
```
:12345 {
        file_server
        encode zstd gzip
        try_files {path}  /index.html
}
```
