### ISSUE TITLE
[nightly] WebDAV audio requests not loading due to CORS errors in Safari

### ISSUE THREAD

**Issue by icidasset** [icidasset/diffuse#434]
Playback issues on iOS using WebDAV. Works fine in Chromium & Firefox.

**Comment by icidasset** [comment]
Turns out I needed to put `X-Playback-Session-Id` on the allowed CORS headers 🤯 Some requests in the network tab still produce an error, but at least the audio is playing now.
```yaml
cors:
  allowed_headers:
    - Authorization
    - Depth
    - X-Playback-Session-Id
  allowed_methods:
    - GET
    - HEAD
    - OPTIONS
    - PROPFIND
  allowed_hosts:
    - https://diffuse.sh
    - https://nightly.diffuse.sh
    - http://127.0.0.1:44999
    - http://127.0.0.1:8000
    - http://localhost:8000
  exposed_headers:
    - Accept-Ranges
    - Content-Length
    - Content-Range
```
